name             'cookbooks/prueba'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures cookbooks/prueba'
long_description 'Installs/Configures cookbooks/prueba'
version          '0.1.0'
